##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: haddy-uscold-fitness-sep-3-2021-9
spec:
  template:
    metadata:
      name: haddy-uscold-fitness-sep-3-2021-9
    spec:
      serviceAccountName: k8
      hostIPC: True
      containers:
      - name: yolov5
        image: us.gcr.io/sodium-carving-227300/yolov5:5dec2020_v3
        command: ["/bin/sh", "-c"]
        args: ["mkdir /data && 
               gsutil -m cp -r gs://voxel-datasets/derived/voxel/9-3-2021/yolo/* /data/ && 
               gsutil -m cp -r gs://voxel-users/harishma/detector_experiments/yolov5/haddy-uscold-fitness-sep-3-2021/*.yaml /data/config.yaml && 
               gsutil cp gs://voxel-users/common/WandB/.netrc /root/ && 
               python3 train.py --epochs 50 --data /data/config.yaml --img 1024 --weights yolov5l.pt --name haddy_uscold_fitness_sep_3_2021 --cfg yolov5l.yaml --batch-size 4 && 
               gsutil cp -r runs/train/* gs://voxel-users/harishma/detector_experiments/yolov5/haddy-uscold-fitness-sep-3-2021/output"]
        resources:
          limits:
            cpu: 8
            nvidia.com/gpu: 1
            memory: "50Gi"
            ephemeral-storage: "40Gi"
          requests:
            cpu: 8
            memory: "50Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: "40Gi"
      # Do not restart containers after they exit
      restartPolicy: Never
  # of retries before marking as failed.
  backoffLimit: 0
