".*":
  incident:
    dry_run: true
    monitors_requested: []
    state_machine_monitors_requested: [bad_posture]
    incident_machine_params:
      bad_posture:
        should_not_apply_actor_supressions: true
