#
# Copyright 2020-2021 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#
#
camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/western_carriers-north_bergen-0001/1668573441613
  version: 6
camera_uuid: western_carriers/north_bergen/0001/cha
incident:
  incident_machine_params:
    high_vis_hat_or_vest:
      per_camera_cooldown_s: 3600
  monitors_requested: []
  state_machine_monitors_requested:
    - bad_posture
    - no_ped_zone
    - no_stop_at_aisle_end
    - overreaching
    - parking
    - spill
    - high_vis_hat_or_vest
perception:
  detector_tracker:
    actor2class:
      PERSON: 0
      PIT: 1
    height: 736
    model_path: artifacts_01_18_2023_piston-automotive-yolo/best_736_1280.engine
    width: 1280
  door_classifier:
    enabled: false
  hat_classifier:
    enabled: True
    min_actor_pixel_area: 2000
    model_path: artifacts_hard_hat_occlusion_vit_v4_2022-11-18-jit/hard_hat_occlusion_vit_v4_2022-11-18-jit.pt
    is_classification_by_detection: False
  lift_classifier:
    enabled: true
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  pose:
    enabled: true
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  reach_classifier:
    enabled: true
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
    model_type: DL
  vest_classifier:
    enabled: True
    min_actor_pixel_area: 2000
    model_path: artifacts_04_18_2023_voxel_safetyvest_vit_general_2022-09-21-jit/voxel_safetyvest_vit_general_2022-09-21-jit.pt
    model_type: Transformers ##ConvNet Detection
  spill:
    enabled: True
    model_path: artifacts_02_05_2023_spill_generalized_jit/smp-bd6b62dfd5b64dcfb4970102e2c9b2aa-jit.pt
    min_run_time_difference_ms: 15000
    min_pixel_size: 200
    # The max_consequitive_runs do not have any effect unless the max_frame_segments in temporal also has the same value to store the results from these consecutive runs.
    max_consecutive_runs: 1
    post_process_enabled: True
    frame_segment2class: { UNKNOWN: 0, SPILL: 1 }
publisher:
  organization_key: WESTERN_CARRIERS
temporal:
  max_frame_segments: 9
