##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##

camera_uuid: americold/bloomingdale/0005/1648928312947

camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/americold-savannah-bloomingdale-0005/1648928312947
  fps: 5
  version: 2

perception:
  detector_tracker:
    model_path: artifacts_2021-12-06-00-00-00-0000-yolo/best_608_1024.engine
    width: 1024
    height: 608
    actor2class: { PERSON: 0, PIT: 1 }
  pose:
    enabled: True
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  lift_classifier:
    enabled: False
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  reach_classifier:
    enabled: True
    model_type: DL ##DT (DL: Deep learning based, DT: Decision Tree based, HM: Heuristic Model)
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
  door_classifier:
    enabled: False
    model_path: artifacts_door_classifier_resnet50_20211129/door_classifier_resample_resnet50_traced_model.pth
  vest_classifier:
    enabled: False
    model_type: Transformers ##ConvNet Detection
    model_path: artifacts_vit_vest/voxel_safetyvest_vit_2022-04-18.pth # artifacts_attention_vestclassifier/voxel_safety_vest_classifier_attention_resnet_focal_loss_gamma1.5_WS_2022-03-03.pth
  hat_classifier:
    enabled: False

temporal:
  max_past_frames: 60
  max_future_frames: 30
  expire_threshold_ms: 120000

incident:
  incident_enabled: True
  monitors_requested: [bad_posture]
  incident_machine_enabled: True
  state_machine_monitors_requested: [overreaching]
  dry_run: False
  # This directory must be bind-mounted from Docker host
  temp_directory: /var/tmp/voxel/incidents
  generate_temp_subdirs: True

publisher:
  enabled: True
  portal_host: https://app.staging.voxelai.com
  auth_token: fa186d237d08239cc0cf3c548bedf19cd3b00ddb
  organization_key: VOXEL_SANDBOX

state:
  enabled: False
  frames_to_buffer: 1000
  add_epoch_time: False
  publisher:
    batch_max_latency_seconds: 60
    retry_deadline_seconds: 600
    batch_max_message: 1000
    batch_max_bytes: 1000000
    state_topic: projects/sodium-carving-227300/topics/voxel-production-state-messages
    event_topic: projects/sodium-carving-227300/topics/voxel-production-event-messages
    emulator_host: null
