##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
camera_uuid: uscold/laredo/room_f1/cha
camera_url:
  { { JINJA_PARSER(name="camera_url", val_type="str", required=True) } }

camera:
  min_frame_difference_ms: 85

perception:
  detector_tracker:
    model_path: artifacts_yolo-person-pit-exp2-dataset3/best.torchscript.pt
    vest_model_path: "artifacts_vest_classifier-9-19/vest_classifier_resnet18_traced_model.pth"
    height: 480
    width: 960
    actor2class: { PERSON: 0, PIT: 1, HARD_HAT: 2, SAFETY_VEST: 3 }
    should_do_temporal_propagation: 0
  pose:
    enabled: True
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  lift_classifier:
    enabled: true
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  door_classifier:
    enabled: True
    model_path: artifacts_door_classifier_resnet50_dataset4/voxel_door_classifier_dataset4_resnet50_traced_model.pth

temporal:
  max_past_frames: 60
  max_future_frames: 30
  expire_threshold_ms: 120000

incident:
  monitors_requested: [intersection]
  dry_run: False
  # This directory must be bind-mounted from Docker host
  temp_directory: /var/tmp/voxel/incidents
  generate_temp_subdirs: True

publisher:
  enabled: True
  portal_host: https://portal.internal.voxelsafety.com
  auth_token: b1288a3615f620b2cb2a0ee8a600780723c9f0ee
  organization_key: USCOLD

state:
  enabled: True
  frames_to_buffer: 1000
  add_epoch_time: True
  publisher:
    batch_max_latency_seconds: 60
    retry_deadline_seconds: 600
    batch_max_message: 1000
    batch_max_bytes: 1000000
    state_topic: projects/sodium-carving-227300/topics/voxel-internal-state-messages
    event_topic: projects/sodium-carving-227300/topics/voxel-internal-event-messages
    emulator_host: null
