#
# Copyright 2020-2021 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#
#
camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/uscold-quakertown-0003/1660237262679
  version: 7
camera_uuid: uscold/quakertown/0003/cha
incident:
  #TODO(delorean): remove this when the experiment is over
  should_generate_on_cooldown: True
  incident_machine_params:
    hard_hat:
      max_no_hat_s: 3
    parking:
      max_parked_duration_s: 300
  monitors_requested: []
  state_machine_monitors_requested:
    - bad_posture
    - hard_hat
    - overreaching
    - parking
    - safety_vest
    - spill

perception:
  enabled: True
  acausal_layer:
    PPESmoothener:
      pose_points_min_confidence_threshold: 0.5
  detector_tracker:
    actor2class:
      PERSON: 0
      PIT: 1
    height: 736
    model_path: artifacts_2022-10-04-18-20-08-f6eb-yolo/best_736_1280.engine
    width: 1280
  door_classifier:
    enabled: false
  hat_classifier:
    enabled: true
    is_classification_by_detection: false
    min_actor_pixel_area: 2000
    model_path: artifacts_hard_hat_occlusion_vit_v4_2022-11-18-jit/hard_hat_occlusion_vit_v4_2022-11-18-jit.pt
  lift_classifier:
    enabled: true
    model_type: HM ##( HM: Heuristic Model, DT : Decision Tree based)
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  pose:
    enabled: true
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  reach_classifier:
    enabled: true
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
    model_type: DL
  vest_classifier:
    enabled: true
    min_actor_pixel_area: 2000
    model_path: artifacts_04_18_2023_voxel_safetyvest_vit_quakertown_laredo_2022_08_24_jit/voxel_safetyvest_vit_quakertown_laredo_2022-08-24-jit.pt
    model_type: Transformers
  spill:
    enabled: True
    model_path: artifacts_02_05_2023_spill_generalized_jit/smp-bd6b62dfd5b64dcfb4970102e2c9b2aa-jit.pt
    min_run_time_difference_ms: 15000
    min_pixel_size: 200
    # The max_consequitive_runs do not have any effect unless the max_frame_segments in temporal also has the same value to store the results from these consecutive runs.
    max_consecutive_runs: 1
    post_process_enabled: True
    frame_segment2class: { UNKNOWN: 0, SPILL: 1 }
  carry_object_classifier:
    enabled: True
    min_actor_pixel_area: 2000
    model_path: artifacts_03_24_2023_carry_classifier_jit/best_lift_DSv4_RN34-jit.pt
    prediction2class:
      NOT_CARRYING: 0
      CARRYING: 1
publisher:
  organization_key: USCOLD
temporal:
  max_frame_segments: 9
