##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##

data_path: /home/nasha/data/datasets/spills/test
model_path: /home/nasha/data/models/spills
codes: [Background, Spill, Floor]
validation_path: /home/nasha/data/datasets/spills/validation/validation_spill.txt
batch_size: 2
learning_rate: 0.0005
n_epochs: 1
model: resnet34
optimizer: ranger_optimzer
loss: dice_loss
image_size: [1080,610]