neo4j:
  resources:
    cpu: 2000m
    memory: 4Gi

volumes:
  data:
    mode: dynamic
    dynamic:
      storageClassName: gp3-retain
      accessModes:
        - ReadWriteOnce
      requests:
        storage: 20Gi

services:
  neo4j:
    enabled: true
    spec:
      type: ClusterIP

  internals:
    enabled: true

config:
  server.default_listen_address: "0.0.0.0"
  server.directories.plugins: "/var/lib/neo4j/labs"
  dbms.security.procedures.unrestricted: "apoc.*"
  server.config.strict_validation.enabled: "false"
  dbms.security.procedures.allowlist: "gds.*,apoc.*"

apoc_config:
  apoc.trigger.enabled: "true"
  apoc.jdbc.neo4j.url: "jdbc:foo:bar"
  apoc.import.file.enabled: "true"