names:
- SPILL
nc: 2
data_extraction_bucket: voxel-users
data_extraction_relative_path: common/spill_data
model_save_relative_path: common/spill_experiments
data_path: /data
model_path: /model
batch_size: 4
n_epochs: 10
synthetic_sample_ratio: 0.5
real_sample_ratio: 1
dataset_type: smp_segmentation
model: smp
augmentation: albumentations
is_augmented: true
download_all_data: true
test: []
train:
- uscold/laredo/dock01/img
- uscold/laredo/dock03/img
- uscold/laredo/dock04/img
- uscold/laredo/doors14_20/img
- uscold/laredo/room_d1p/img
- uscold/laredo/room_d2/img
- uscold/laredo/room_d3/img
- uscold/laredo/room_d4/img
- uscold/laredo/room_d5p/img
- uscold/laredo/room_f1/img
- uscold/quakertown/0003/img
- uscold/quakertown/0004/img
- uscold/quakertown/0006/img
- uscold/quakertown/0007/img
- uscold/quakertown/0008/img
- uscold/quakertown/0009/img
- hensley/chandler/0001/img
- hensley/chandler/0002/img
- hensley/chandler/0003/img
- hensley/chandler/0004/img
- hensley/chandler/0005/img
- hensley/chandler/0006/img
- hensley/chandler/0007/img
- hensley/phoenix/0001/img
- hensley/phoenix/0002/img
- hensley/phoenix/0004/img
- hensley/phoenix/0003/img
- hensley/phoenix/0005/img
- hensley/phoenix/0006/img
- americold/vineland/0009/img
- americold/vineland/0008/img
- americold/vineland/0007/img
- americold/vineland/0003/img
- americold/vineland/0001/img
- americold/vineland/0002/img
- americold/vineland/0006/img
- americold/tacoma/0001/img
- americold/tacoma/0003/img
- americold/tacoma/0004/img
- americold/tacoma/0005/img
- americold/tacoma/0007/img
- ppg/cedar_falls/0001/img
- ppg/cedar_falls/0002/img
- ppg/cedar_falls/0003/img
- ppg/cedar_falls/0005/img
- ppg/cedar_falls/0007/img
- ppg/cedar_falls/0008/img
- ppg/cedar_falls/0011/img
- ppg/cedar_falls/0010/img
- feb_distributing/biloxi/0003/img
- feb_distributing/biloxi/0004/img
- feb_distributing/biloxi/0005/img
- feb_distributing/biloxi/0006/img
- trieagle/ocala/0007/img
- trieagle/ocala/0008/img
- trieagle/ocala/0009/img
- trieagle/ocala/0010/img
- lakeshore_beverage/arlington_heights/0010/img
- lakeshore_beverage/arlington_heights/0009/img
- lakeshore_beverage/arlington_heights/0008/img
- lakeshore_beverage/arlington_heights/0007/img
- lakeshore_beverage/arlington_heights/0006/img
- lakeshore_beverage/arlington_heights/0005/img
- lakeshore_beverage/arlington_heights/0004/img
- lakeshore_beverage/arlington_heights/0003/img
- lakeshore_beverage/arlington_heights/0002/img
- lakeshore_beverage/arlington_heights/0001/img
- buildersfirstsource/solanabeach/0008/img
- buildersfirstsource/solanabeach/0007/img
- americold/taunton/0010/img
- americold/taunton/0009/img
- americold/taunton/0005/img
- americold/tacoma/0007/img
- americold/tacoma/0005/img
- americold/tacoma/0004/img
- americold/tacoma/0003/img
- americold/tacoma/0001/img
- americold/savannah_pooler/0010/img
- americold/savannah_pooler/0009/img
- americold/savannah_pooler/0008/img
- americold/savannah_pooler/0007/img
- americold/savannah_pooler/0006/img
- americold/savannah_pooler/0005/img
- americold/savannah_pooler/0004/img
- americold/savannah_pooler/0003/img
- americold/savannah_pooler/0002/img
- americold/savannah_pooler/0001/img
- americold/savannah_bloomingdale/0007/img
- americold/savannah_bloomingdale/0006/img
- americold/savannah_bloomingdale/0003/img
- americold/savannah_bloomingdale/0001/img
- americold/sanford/0010/img
- americold/sanford/0009/img
- americold/sanford/0008/img
- americold/sanford/0007/img
- americold/sanford/0006/img
- americold/sanford/0005/img
- americold/sanford/0004/img
- americold/sanford/0003/img
- americold/sanford/0002/img
- americold/sanford/0001/img
- americold/ontario/0013/img
- americold/ontario/0012/img
- americold/ontario/0011/img
- americold/ontario/0010/img
- americold/ontario/0006/img
- americold/ontario/0004/img
- americold/ontario/0003/img
- americold/ontario/0001/img
- americold/modesto/0010/img
- americold/modesto/0009/img
- americold/modesto/0004/img
- americold/modesto/0002/img
- western_carriers/north_bergen/0007/img
- western_carriers/north_bergen/0005/img
- western_carriers/north_bergen/0004/img
- western_carriers/north_bergen/0003/img
- western_carriers/north_bergen/0002/img
- western_carriers/north_bergen/0001/img
- innovate_manufacturing/knoxville/0004/img
- wn_foods/hayward/0008/img