#
# Copyright 2023 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#


pull_kinesis_feed_site:
   hours: 0.05
   chunk_size: 3
  
create_scale_tasks:
    credentials_arn: "arn:aws:secretsmanager:us-west-2:203670452561:secret:scale_test_credentials-E77TFB"
    dry_run: True