# Default filesystem storage class, should be one replica.
replicaCount: 1

image:
  repository: privatebin/nginx-fpm-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

controller:
  kind: StatefulSet
  pvc:
    requests: 8Gi
    accessModes: ReadWriteOnce
    storageClass: gp3-retain

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: privatebin.voxelplatform.com
      paths:
        - path: /
          pathType: Prefix

resources: {}

configs:
  conf.php: |-
    [main]
    discussion = false
    opendiscussion = false
    password = true
    fileupload = true
    burnafterreadingselected = false
    defaultformatter = "plaintext"
    sizelimit = 10485760
    template = "bootstrap"
    qrcode = false
    compression = "zlib"
    notice = "Note: Do not store any sensetive info or credentials. Access may be logged and audited."

    [expire]
    default = "1day"

    [expire_options]
    5min = 300
    10min = 600
    1hour = 3600
    1day = 86400
    1week = 604800
    30days = 2592000

    [formatter_options]
    plaintext = "Plain Text"
    syntaxhighlighting = "Source Code"
    markdown = "Markdown"

    [traffic]
    limit = 10

    [purge]
    limit = 300
    batchsize = 10

    [model]
    class = Filesystem
    [model_options]
    dir = PATH "data"