#
# Copyright 2020-2021 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#
#
camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/ppg-cedar_falls-0004/1668827596827
  version: 5
camera_uuid: ppg/cedar_falls/0004/cha
incident:
  incident_machine_params:
    parking:
      max_parked_duration_s: 600
  monitors_requested: []
  state_machine_monitors_requested:
    - bad_posture
    - n_person_ped_zone
    - parking
    - spill
perception:
  detector_tracker:
    actor2class:
      PERSON: 0
      PIT: 1
    height: 736
    model_path: artifacts_01_18_2023_piston-automotive-yolo/best_736_1280.engine
    width: 1280
  door_classifier:
    enabled: false
  hat_classifier:
    enabled: false
    is_classification_by_detection: false
    min_actor_pixel_area: 2000
    model_path: artifacts_bumpcap_vit_99_46_34k_2022-12-20-jit/bumpcap_vit_99_46_34k_2022-12-20-jit.pt
  lift_classifier:
    enabled: true
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  pose:
    enabled: true
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  reach_classifier:
    enabled: true
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
    model_type: DL
  vest_classifier:
    enabled: false
    min_actor_pixel_area: 800
    model_path: artifacts_04_18_2023_voxel_safetyvest_vit_general_2022-09-21-jit/voxel_safetyvest_vit_general_2022-09-21-jit.pt
    model_type: Transformers
  spill:
    enabled: True
    model_path: artifacts_02_05_2023_spill_generalized_jit/smp-bd6b62dfd5b64dcfb4970102e2c9b2aa-jit.pt
    min_run_time_difference_ms: 15000
    min_pixel_size: 200
    # The max_consequitive_runs do not have any effect unless the max_frame_segments in temporal also has the same value to store the results from these consecutive runs.
    max_consecutive_runs: 1
    post_process_enabled: True
    frame_segment2class: {UNKNOWN: 0, SPILL: 1}
  carry_object_classifier:
    enabled: True
    min_actor_pixel_area: 2000
    model_path: artifacts_03_24_2023_carry_classifier_jit/best_lift_DSv4_RN34-jit.pt
    prediction2class:
      NOT_CARRYING: 0
      CARRYING: 1
publisher:
  organization_key: PPG
temporal:
  max_frame_segments: 9