#
# Copyright 2020-2021 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#
#
camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/wn_foods-hayward-0004/1663697430766
  version: 4
camera_uuid: wn_foods/hayward/0004/cha
incident:
  incident_machine_params: {}
  monitors_requested: []
  state_machine_monitors_requested:
    - production_line_down
perception:
  detector_tracker:
    actor2class:
      PERSON: 0
      PIT: 1
    height: 736
    model_path: artifacts_2022-11-15-03-38-16-91db-yolo/best_736_1280.engine
    width: 1280
  door_classifier:
    enabled: false
  hat_classifier:
    enabled: false
  lift_classifier:
    enabled: false
  motion_zone_detection:
    enabled: true
    gaussian_kernel_size: 3
    variance_threshold: 40
    bg_frames_history: 5
  pose:
    enabled: false
  reach_classifier:
    enabled: false
  vest_classifier:
    enabled: false
publisher:
  organization_key: WN_FOODS
