apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}