##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##

camera_uuid: uscold/laredo/dock01/cha

camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/uscold-laredo-0001/1651957466439
  version: 5

perception:
  enabled: True
  acausal_layer:
    PPESmoothener:
      time_interval_ms: 10000
      pose_points_min_confidence_threshold: 0.5
  detector_tracker:
    model_path: artifacts_2021-12-06-00-00-00-0000-yolo/best_608_1024.engine
    height: 608
    width: 1024
    actor2class: { PERSON: 0, PIT: 1}
  pose:
    enabled: True
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  lift_classifier:
    enabled: true
    model_type: HM ##( HM: Heuristic Model, DT : Decision Tree based)
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  reach_classifier:
    enabled: True
    model_type: DL ##DT (DL: Deep learning based, DT: Decision Tree based, HM: Heuristic Model)
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
  door_classifier:
    enabled: False
    model_path: artifacts_door_classifier_resnet50_dataset4/voxel_door_classifier_dataset4_resnet50_traced_model.pth
  vest_classifier:
    enabled: False
    model_type: Transformers ##ConvNet Detection
    min_actor_pixel_area: 2000
    model_path: artifacts_04_18_2023_voxel_safetyvest_vit_laredo-2_laredo_2022-09-15-jit/voxel_safetyvest_vit_laredo-2_laredo_2022-09-15-jit.pt
  hat_classifier:
    enabled: False
    model_path: artifacts_hard_hat_occlusion_vit_v4_2022-11-18-jit/hard_hat_occlusion_vit_v4_2022-11-18-jit.pt
    is_classification_by_detection: False
  spill:
    enabled: True
    model_path: artifacts_02_05_2023_spill_generalized_jit/smp-bd6b62dfd5b64dcfb4970102e2c9b2aa-jit.pt
    min_run_time_difference_ms: 15000
    min_pixel_size: 200
    # The max_consequitive_runs do not have any effect unless the max_frame_segments in temporal also has the same value to store the results from these consecutive runs.
    max_consecutive_runs: 1
    post_process_enabled: True
    frame_segment2class: { UNKNOWN: 0, SPILL: 1 }
  carry_object_classifier:
    enabled: True
    min_actor_pixel_area: 2000
    model_path: artifacts_03_24_2023_carry_classifier_jit/best_lift_DSv4_RN34-jit.pt
    prediction2class:
      NOT_CARRYING: 0
      CARRYING: 1

incident:
  #TODO(delorean): remove this when the experiment is over
  should_generate_on_cooldown: True
  monitors_requested: []
  state_machine_monitors_requested: [overreaching, spill, bad_posture]

publisher:
  organization_key: USCOLD
