model:
  # Spill Configs
  artifact_model_paths:
        - artifacts_02_05_2023_spill_generalized_jit/smp-bd6b62dfd5b64dcfb4970102e2c9b2aa-jit.pt
  disable_warmup_generation: true
  config:
    platform: pytorch_libtorch
    max_batch_size: 128
    input:
      - name: images
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [3, -1, -1]
    output:
      - name: output0
        data_type: TYPE_FP32
        dims: [1, -1, -1]