##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
name: "VanillaResnet50"
params:
  config:
    device: cuda:0
    seed: 1234
    mode: train
    dataset: "/data"
    classifier:
      name: &classifier_name "door_classifier"
    model_path: /model
    data:
      dataloader_name: image_from_dataframe
      dataloader_params:
        data_path: /data
        valid_pct: 0.1
        batch_size: 32
        use_weighted_random_sampler: true
      transforms:
        - name: Resize
          params:
            size: [224, 224]
        - name: ToTensor
          params: {}
        - name: Normalize
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      augmentation_transforms: {}

    model_parameters:
      name: &model_name ""
      params:
        num_classes: 3
      type: VanillaResnet
      metrics: acc_f1_prec_rec
      conf_matrix: true

    loss:
      name: &loss_name ema
      params:
        alpha: 0.25
        gamma: 1.5
        reduction: "mean"
      use_cross_entropy: 0
      label_smooth: 0

    optimizer:
      n_epoch: &nepoch 24
      lr: &lr 0.001

    scheduler:
      step: &s 7
      gamma: 0.1
    logging:
      - name: console
