##
## Copyright 2020-2022 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##

name: "ViTClassifierModel"
params:
  config:
    model:
      loss: "CrossEntropyLoss"
      optimizer: "Adam"
      optimizer_params:
          lr: 0.0001
    training:
        gpus: 1
        min_epochs: 10
        max_epochs: 10
    data:
      transforms:
        - name: ViTFeatureExtractorTransform
          params: 
            pretrained_model: "google/vit-base-patch16-224-in21k"