#
# Copyright 2020-2021 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#
#
camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/wesco-reno-0008/1673393066778
  version: 2
camera_uuid: wesco/reno/0008/cha
incident:
  incident_machine_params:
    open_door:
      max_open_door_s: 30
    parking:
      max_parked_duration_s: 300
    safety_vest:
      max_no_vest_s: 10
  monitors_requested: []
  state_machine_monitors_requested:
    - open_door
    - parking
    - safety_vest
perception:
  detector_tracker:
    actor2class:
      PERSON: 0
      PIT: 1
    height: 736
    model_path: artifacts_02_27_2023_michaels_wesco_office_yolo/best_736_1280.engine
    width: 1280
  door_classifier:
    enabled: true
    model_path: artifacts_02_06_2023_generalized_EXIT_Door_new/7547a635-1ae9-4b9a-b44a-4e8991269ead.pt
    model_type: vanilla_resnet
  hat_classifier:
    enabled: false
  lift_classifier:
    enabled: true
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  pose:
    enabled: true
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  reach_classifier:
    enabled: true
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
    model_type: DL
  vest_classifier:
    enabled: True
    min_actor_pixel_area: 2000
    model_path: artifacts_04_18_2023_voxel_safetyvest_vit_general_2022-09-21-jit/voxel_safetyvest_vit_general_2022-09-21-jit.pt
    model_type: Transformers ##ConvNet Detection:
publisher:
  organization_key: WESCO
