enabled: true
environment: ${ENVIRONMENT}
image:
  repository: ${PORTAL_REPO}
  pullPolicy: Always
  tag: ${PORTAL_IMAGE_TAG}

command: "/app/core/portal/tools/message_processor"
args: [${COMMAND_ARG}]
non_web_app: true

ingress:
  enabled: false

serviceAccount:
  name: ${SERVICE_ACCOUNT_NAME}
  create: false

secrets:
  name: secret-store
  mountPath: /mnt/secrets-store
  secretProviderClass: ${SECRET_PROVIDER_NAME}

service:
  type: ClusterIP
  containerPort: 8080
resources:
  requests:
    cpu: 512m
    memory: 2048Mi
  limits:
    cpu: 512m
    memory: 2048Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

livenessProbe:
  failureThreshold: 6
  httpGet:
    path: /api/health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 30

readinessProbe:
  failureThreshold: 6
  httpGet:
    path: /api/health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 30


env:
  config:
    SECRETS_FILEPATH: /mnt/secrets-store/portal
    SECRETS_GOOGLE_SERVICE_ACCOUNT_JSON_FILEPATH: /mnt/secrets-store/portal_google_service_account_json
    BASE_URL: https://${DOMAIN}
