codecov:
  bot: codecov
  ci:
    - buildkite.com
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        # Do not gate for now.
        informational: true
github_checks:
  annotations: true
