##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: haddy-detectron2-mpii-custom-3
spec:
  template:
    metadata:
      name: haddy-detectron2-mpii-custom-3
    spec:
      serviceAccountName: k8
      hostIPC: True
      containers:
      - name: detectron2
        image: us.gcr.io/sodium-carving-227300/voxel/experimental:haddy_1628903014
        command: ["/bin/sh", "-c"]
        args: ["apt update && mkdir /data && gsutil -m cp -r gs://voxel-users/common/mpii/* /data/ && ls /data/ && gsutil cp gs://voxel-users/common/WandB/.netrc ~/ && /app/experimental/haddy/detectron2/train_mpii_custom.runfiles/python_interpreter_3_8_10/python /app/experimental/haddy/detectron2/train_mpii_custom -lr 0.02 -epochs 50 -out_dir /data/output -data_dir /data -wandb_name haddy-detectron2-mpii-custom-2 -num_gpus 1
 && gsutil cp -r /data/output/* gs://voxel-users/haddy/experiments/detectron2/haddy-detectron2-mpii-custom-3"]
        resources:
          limits:
            cpu: 8
            nvidia.com/gpu: 1
            memory: "50Gi"
            ephemeral-storage: "40Gi"
          requests:
            cpu: 8
            memory: "50Gi"
            nvidia.com/gpu: 1
            ephemeral-storage: "40Gi"
      # Do not restart containers after they exit
      restartPolicy: Never
  # of retries before marking as failed.
  backoffLimit: 1