##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
---
version: "3.9"
services:
  camera_1:
    image: 667031391229.dkr.ecr.us-west-2.amazonaws.com/voxel/edge_smoke_test:troy_voxelsafety_com_1630370512
    command:
      - --camera_config_path=configs/cameras/experimental/edge_sandbox.yaml
    ports:
      - "8080"
    ipc: host
    restart: unless-stopped
    volumes:
      - /var/tmp/voxel:/var/tmp/voxel
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
  camera_2:
    image: 667031391229.dkr.ecr.us-west-2.amazonaws.com/voxel/edge_smoke_test:troy_voxelsafety_com_1630370512
    command:
      - --camera_config_path=configs/cameras/experimental/edge_sandbox.yaml
    ports:
      - "8080"
    ipc: host
    restart: unless-stopped
    volumes:
      - /var/tmp/voxel:/var/tmp/voxel
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
