##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##

data:
  path: "/home/nasha_voxelsafety_com/voxel/experimental/shared/ppe/scenario_test_full"
  labels: ["no_vest", "vest"]
  width: 1024
  height: 608
model:
  path: '/home/nasha_voxelsafety_com/voxel/experimental/nasha/models/ppe_detector/traced_detr.pt'
  type: "DETR"
experiments:
  name: "production_vest_detector"
  object: "SAFETY_VEST"
  cropped: 1