##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
apiVersion: v1
kind: Pod
metadata:
  name: redis-cache
  labels:
    app: redis
spec:
  containers:
  - name: redis-cache
    image: redis
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  ports:
  - name: redis-port
    nodePort: 31005
    protocol: "TCP"
    port: 6379
    targetPort: 6379
  selector:
    app: redis