##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
apiVersion: v1
kind: Pod
metadata:
  name: timescale-db
  labels:
    app: timescale
spec:
  containers:
  - name: timescale-db
    image: timescale/timescaledb:latest-pg13
    env:
    - name: POSTGRES_PASSWORD
      value: voxelvoxel
    - name: POSTGRES_USER
      value: voxelapp
    - name: POSTGRES_DB
      value: voxeldev
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: timescale-svc
spec:
  type: NodePort
  ports:
  - name: timescale-port
    nodePort: 31004
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: timescale