ensemble:
# Object Detection 2D Ensemble
  primary_model_name: yolo_model
  artifact_model_paths:
    - artifacts_2021-12-06-00-00-00-0000-yolo/best_480_960.engine
  config:
    platform: ensemble
    max_batch_size: 1
    input:
      - name: INPUT_0
        data_type: TYPE_UINT8
        format: FORMAT_NHWC
        dims: [-1, -1, 3]
      - name: INPUT_1
        data_type: TYPE_INT32
        dims: [2]
      - name: INPUT_2
        data_type: TYPE_INT32
        dims: [-1]
      - name: INPUT_3
        data_type: TYPE_FP16
        dims: [1]
      - name: INPUT_4
        data_type: TYPE_FP16
        dims: [1]
    output:
      - name: output0
        data_type: TYPE_INT64
        dims: [1]
      - name: output1
        data_type: TYPE_FP32
        dims: [9]
    ensemble_scheduling:
      step:
        - model_name: artifacts_yolo_v5_pre_processing_04_13_2023/yolo_torchscript_preprocess_apr_13.pt
          model_version: 1
          input_map:
            INPUT_0: INPUT_0
            INPUT_1: INPUT_1
          output_map:
            OUTPUT_0: images
            OUTPUT_1: offset
            OUTPUT_2: scale
        - model_name: yolo_model
          model_version: 1
          input_map:
            images: images
          output_map:
            output0: predictions
        - model_name: artifacts_yolo_v5_post_processing_04_11_2023/yolo_torchscript_postprocess_apr_11.pt
          model_version: 1
          input_map:
            input0: predictions
            input1: offset
            input2: scale
            input3: INPUT_2
            input4: INPUT_3
            input5: INPUT_4
          output_map:
            output0: output0
            output1: output1