model:
  artifact_model_paths:
        - artifacts_yolo_v5_pre_processing_04_13_2023/yolo_torchscript_preprocess_apr_13.pt
  disable_warmup_generation: true
  config:
    platform: pytorch_libtorch
    max_batch_size: 16
    input:
      - name: INPUT_0
        data_type: TYPE_UINT8
        format: FORMAT_NHWC
        dims: [-1, -1, 3]
      - name: INPUT_1
        data_type: TYPE_INT32
        dims: [2]
    output:
      - name: OUTPUT_0
        data_type: TYPE_FP16
        dims: [3, -1, -1]
      - name: OUTPUT_1
        data_type: TYPE_FP32
        dims: [2]
      - name: OUTPUT_2
        data_type: TYPE_FP32
        dims: [2]