non_web_app: true

autoscaling:
  enabled: true
  minReplicas: 2

image:
  repository: "tailscale/tailscale"

service:
  containerPort: 8080

args: ["up", "--advertise-routes=10.0.0.0/24,10.0.1.0/24", "--authkey=${TS_AUTH_KEY}"]

env:
  config:
    TUNNEL_METRICS: "localhost:8080"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/instance"
              operator: In
              values:
                - ${DEPLOYMENT_IDENTIFIER}
        topologyKey: "kubernetes.io/hostname"
