##
## Copyright 2020-2021 Voxel Labs, Inc.
## All rights reserved.
##
## This document may not be reproduced, republished, distributed, transmitted,
## displayed, broadcast or otherwise exploited in any manner without the express
## prior written permission of Voxel Labs, Inc. The receipt or possession of this
## document does not convey any rights to reproduce, disclose, or distribute its
## contents, or to manufacture, use, or sell anything that it may describe, in
## whole or in part.
##
calibration:
    version: 0.0
    intrinsics:
        # focal length in pixels based on a 299x299 image
        focal_length_pixels: 459.45546
        # distortion using the unified spherical model
        distortion_usm: 0.842461
        width_pixels:  608
        height_pixels: 1024
        cx_pixels: 304
        cy_pixels: 512
    extrinsics:
        z_m: 10.199
        roll_radians: -0.4840
        pitch_radians: -0.0157
