model:
  # Door State Configs
  artifact_model_paths:
      - artifacts_2022-10-26_americold_modesto_0001_cha/2022-10-26_americold_modesto_0001_cha.pt
      - artifacts_2022-10-26_americold_modesto_0002_cha/2022-10-26_americold_modesto_0002_cha.pt
      - artifacts_2022-10-26_americold_modesto_0003_cha/2022-10-26_americold_modesto_0003_cha.pt
      - artifacts_2022-10-26_americold_modesto_0005_cha/2022-10-26_americold_modesto_0005_cha.pt
      - artifacts_2022-10-26_americold_modesto_0009_cha/2022-10-26_americold_modesto_0009_cha.pt
      - artifacts_03_05_2023_americold_modesto_0011_cha/256037fe-697a-4484-ab48-8c81b6ea18e1.pt
  disable_warmup_generation: true
  config:
      platform: pytorch_libtorch
      max_batch_size: 16
      input:
        - name: images
          data_type: TYPE_FP32
          format: FORMAT_NCHW
          dims: [3, 224, 224]
      output:
        - name: output0
          data_type: TYPE_FP32
          dims: [3]