image:
  repository: ghcr.io/foxglove/studio
  pullPolicy: Always
  tag: 1.52.0

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  requests:
    cpu: 256m
    memory: 512Mi
  limits:
    cpu: 256m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
