#
# Copyright 2020-2021 Voxel Labs, Inc.
# All rights reserved.
#
# This document may not be reproduced, republished, distributed, transmitted,
# displayed, broadcast or otherwise exploited in any manner without the express
# prior written permission of Voxel Labs, Inc. The receipt or possession of this
# document does not convey any rights to reproduce, disclose, or distribute its
# contents, or to manufacture, use, or sell anything that it may describe, in
# whole or in part.
#
#
camera:
  arn: arn:aws:kinesisvideo:us-west-2:360054435465:stream/uscold-syracuse-0010/1682967684253
  version: 1
camera_uuid: uscold/syracuse/0010/cha
incident:
  incident_machine_params: {}
  monitors_requested: []
  state_machine_monitors_requested:
    - bad_posture
    - door_intersection
    - hard_hat
    - open_door
    - overreaching
    - piggyback
    - safety_vest
perception:
  detector_tracker:
    actor2class:
      PERSON: 0
      PIT: 1
    height: 736
    model_path: artifacts_05_28_2023_vertical_cold_storage_richardson_uscold_syracuse_yolo/best_736_1280.engine
    width: 1280
  door_classifier:
    enabled: true
    model_path: artifacts_05_28_2023_uscold_syracuse_0010_cha/663a5729-6520-4626-9604-60bfe36bb0a9.pt
    model_type: vanilla_resnet
  hat_classifier:
    enabled: true
    is_classification_by_detection: false
    min_actor_pixel_area: 2000
    model_path: artifacts_hard_hat_occlusion_vit_v4_2022-11-18-jit/hard_hat_occlusion_vit_v4_2022-11-18-jit.pt
  lift_classifier:
    enabled: true
    model_path: artifacts_lift_classifier_01282022/lift_classifer_01282022.sav
  motion_zone_detection:
    enabled: false
  pose:
    enabled: true
    model_path: artifacts_03_21_2023_pose_0630_jit_update/fast_res50_256x192.pt
  reach_classifier:
    enabled: true
    model_path: artifacts_03_23_2023_overreaching_model_jit/voxel_ergo_ml_overreaching_2022-05-23-jit.pt
    model_type: DL
  vest_classifier:
    enabled: true
    min_actor_pixel_area: 2000
    model_path: artifacts_04_18_2023_voxel_safetyvest_vit_quakertown_laredo_2022_08_24_jit/voxel_safetyvest_vit_quakertown_laredo_2022-08-24-jit.pt
    model_type: Transformers
publisher:
  organization_key: USCOLD
